## Student Marks Analyzer

In [2]:
# Using NumPy, analyze the marks of 10 students across 5 subjects. Perform the following tasks:

# Find the total marks of each student.
# Find the average marks of each student.
# Find the average marks of each subject.
# Find the highest and lowest marks in the entire dataset.
# Identify students who passed and failed. Passing marks = 50 in each subject.
# Rank the students based on their average marks.

# Assign a grade to each student:
# 80+ = A
# 70–79 = B
# 60–69 = C
# 50–59 = D
# Below 50 = Fail

# Find the student with the highest overall average.
# Normalize the students' average marks between 0 and 1.

## Dataset

In [3]:
import numpy as np

students = np.array([
    [85, 78, 92, 88, 90],
    [72, 68, 75, 80, 70],
    [55, 62, 58, 65, 60],
    [91, 89, 95, 94, 90],
    [45, 52, 48, 50, 43],
    [76, 82, 79, 74, 85],
    [63, 59, 67, 61, 65],
    [88, 91, 84, 86, 89],
    [50, 47, 55, 52, 49],
    [69, 73, 71, 66, 75]
])

**Total marks of each student**

In [4]:
total_marks = np.sum(students[:, 0:], axis=1)
print("Total Marks of Each Student: ", total_marks)

Total Marks of Each Student:  [433 365 300 459 238 396 315 438 253 354]


**Average Marks of Each Student**

In [5]:
Average_Marks_Student = np.mean(students[:, 0:], axis=1)
print("Avergae Marks of Each Student :", Average_Marks_Student)

Avergae Marks of Each Student : [86.6 73.  60.  91.8 47.6 79.2 63.  87.6 50.6 70.8]


**Average Marks of Each Subject**

In [6]:
Average_Marks_Subject = np.mean(students[:, 0:], axis=0)
print("Average Marks of Subject: ", Average_Marks_Subject)

Average Marks of Subject:  [69.4 70.1 72.4 71.6 71.6]


**Highest and lowest Marks in Entire Dataset**

In [7]:
Low_marks = np.min(students[:, :])
print("Low Marks", Low_marks)

High_marks = np.max(students[:, :])
print("High Marks", High_marks)

Low Marks 43
High Marks 95


**Identify Passed and Failed Students**

In [8]:
passed = np.all(students >= 50, axis=1)

print("Passed Students:", np.where(passed)[0] + 1)
print("Failed Students:", np.where(~passed)[0] + 1)

Passed Students: [ 1  2  3  4  6  7  8 10]
Failed Students: [5 9]


**Rank Students**

In [9]:
rank = np.argsort(Average_Marks_Student)[::-1]

print("Ranking:")

for i, student in enumerate(rank):
    print("Rank", i + 1, ": Student", student + 1)

Ranking:
Rank 1 : Student 4
Rank 2 : Student 8
Rank 3 : Student 1
Rank 4 : Student 6
Rank 5 : Student 2
Rank 6 : Student 10
Rank 7 : Student 7
Rank 8 : Student 3
Rank 9 : Student 9
Rank 10 : Student 5


**Assign Grades**

In [10]:
grades = np.where(Average_Marks_Student >= 80, "A",
         np.where(Average_Marks_Student >= 70, "B",
         np.where(Average_Marks_Student >= 60, "C",
         np.where(Average_Marks_Student >= 50, "D", "Fail"))))

print("Grades:", grades)

Grades: ['A' 'B' 'C' 'A' 'Fail' 'B' 'C' 'A' 'D' 'B']


**Student With Highest Average**

In [11]:
Highest_Average = np.max(Average_Marks_Student)

Student_name = np.where(Average_Marks_Student == Highest_Average)

print("Highest Average:", Highest_Average)
print("Student:", Student_name[0] + 1)

Highest Average: 91.8
Student: [4]


**Normalize Average Marks**

In [12]:
normalized = (Average_Marks_Student - np.min(Average_Marks_Student)) / (np.max(Average_Marks_Student) - np.min(Average_Marks_Student))

print("Normalized Averages:", normalized)

Normalized Averages: [0.88235294 0.57466063 0.28054299 1.         0.         0.71493213
 0.34841629 0.90497738 0.0678733  0.52488688]


**Split dataset into training and testing sets**

In [14]:
split_index = int(len(students) * 0.7)

training_data = students[:split_index]
testing_data = students[split_index:]

print("Training Data:")
print(training_data)

print("\nTesting Data:")
print(testing_data)

Training Data:
[[85 78 92 88 90]
 [72 68 75 80 70]
 [55 62 58 65 60]
 [91 89 95 94 90]
 [45 52 48 50 43]
 [76 82 79 74 85]
 [63 59 67 61 65]]

Testing Data:
[[88 91 84 86 89]
 [50 47 55 52 49]
 [69 73 71 66 75]]
